[extension]
name = "nns"
version = "0.1.0"
homepage = "https://github.com/dfinity/dfx-extensions"
authors = "DFINITY"
summary = "Toolkit to interact with the Network Nervous System."
categories = ["sns", "nns"]
keywords = [
    "nns"
    "deployment",
]

[extension.subcommands]
init = {}
import = {}

